// <auto-generated />
using System;
using Geloc.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Geloc.Dados.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20181201202021_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Geloc.Dominio.Contrato", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Acrescimo");

                    b.Property<int>("Adicional");

                    b.Property<DateTime?>("DataCadastro");

                    b.Property<DateTime?>("DataPagamento");

                    b.Property<DateTime?>("DataRetorno");

                    b.Property<DateTime?>("DataSaida");

                    b.Property<decimal>("Desconto");

                    b.Property<int>("EnderecoId");

                    b.Property<int>("Numero");

                    b.Property<string>("Observacao");

                    b.Property<int>("Pago");

                    b.Property<int>("PessoaId");

                    b.Property<int>("Renovado");

                    b.Property<DateTime?>("RetornouEm");

                    b.Property<string>("Situacao");

                    b.Property<string>("TotalEmMetros");

                    b.Property<decimal>("Valor");

                    b.Property<decimal>("ValorAPagar");

                    b.Property<decimal>("ValorDeve");

                    b.Property<decimal>("ValorPago");

                    b.Property<string>("telefonesSelecionados");

                    b.HasKey("ContratoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("Geloc.Dominio.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ativo");

                    b.Property<int>("PessoaId");

                    b.Property<string>("endereco");

                    b.HasKey("EmailId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("Geloc.Dominio.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ativo");

                    b.Property<string>("Bairro");

                    b.Property<string>("CEP");

                    b.Property<string>("Complemento");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Municipio");

                    b.Property<int>("PessoaId");

                    b.Property<string>("Referencia");

                    b.Property<string>("Uf");

                    b.HasKey("EnderecoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Geloc.Dominio.ItemCategoriaContrato", b =>
                {
                    b.Property<int>("ItemCategoriaContratoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaEquipamentoId");

                    b.Property<int>("ContratoId");

                    b.Property<DateTime?>("DataRetorno");

                    b.Property<DateTime?>("DataSaida");

                    b.Property<string>("DescricaoCategoria");

                    b.Property<int>("EnderecoId");

                    b.Property<string>("MedidaPacote");

                    b.Property<string>("NomePacote");

                    b.Property<int>("PacoteAluguelId");

                    b.Property<int>("QuantidadePacotes");

                    b.Property<DateTime?>("RetornouEm");

                    b.Property<int>("UnidadesPorPacote");

                    b.Property<decimal>("ValorPacote");

                    b.Property<decimal>("ValorTotalAPagar");

                    b.Property<decimal>("acrescimoItem");

                    b.Property<decimal>("descontoItem");

                    b.Property<int>("quantidadeAlugada");

                    b.Property<decimal>("valorTotal");

                    b.HasKey("ItemCategoriaContratoId");

                    b.HasIndex("ContratoId");

                    b.ToTable("ItemCategoriaContrato");
                });

            modelBuilder.Entity("Geloc.Dominio.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ativo");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(20);

                    b.Property<string>("CPF")
                        .HasMaxLength(14);

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime?>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Observacao");

                    b.Property<string>("OutrosNoLocal");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Geloc.Dominio.Telefone", b =>
                {
                    b.Property<int>("TelefoneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ativo");

                    b.Property<string>("Numero");

                    b.Property<string>("Observacao");

                    b.Property<string>("Operadora");

                    b.Property<int>("PessoaId");

                    b.Property<string>("TipoTelefone");

                    b.HasKey("TelefoneId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("Geloc.Dominio.Contrato", b =>
                {
                    b.HasOne("Geloc.Dominio.Pessoa")
                        .WithMany("Contratos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Geloc.Dominio.Email", b =>
                {
                    b.HasOne("Geloc.Dominio.Pessoa", "Pessoa")
                        .WithMany("Emails")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Geloc.Dominio.Endereco", b =>
                {
                    b.HasOne("Geloc.Dominio.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Geloc.Dominio.ItemCategoriaContrato", b =>
                {
                    b.HasOne("Geloc.Dominio.Contrato")
                        .WithMany("itensContrato")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Geloc.Dominio.Telefone", b =>
                {
                    b.HasOne("Geloc.Dominio.Pessoa", "Pessoa")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
